apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: devops-catalog-postgres-data
  namespace: devops-catalog

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi