apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: devops-catalog-postgres
  namespace: devops-catalog

spec:
  serviceName: devops-catalog-postgres
  replicas: 1

  selector:
    matchLabels:
      app: devops-catalog-postgres

  template:
    metadata:
      labels:
        app: devops-catalog-postgres

    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine

          ports:
            - containerPort: 5432

          envFrom:
            - secretRef:
                name: devops-catalog-postgres-secret

          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - 'pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"'
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - 'pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"'
            initialDelaySeconds: 15
            periodSeconds: 10

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: devops-catalog-postgres-data